# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: pip

      - name: Install package
        run: |
          python -m pip install --upgrade pip
          pip install .[dev]

      - name: Lint with flake8
        run: |
          flake8 ./src/geopull --count --exit-zero --max-complexity=15 --max-line-length=80 --statistics

      - name: Lint with mypy
        run: |
          mypy

      - name: Lint with black
        uses: psf/black@stable
        with:
          options: "--check --verbose"
          src: "./src/geopull"

      - name: Test with pytest
        run: |
          pytest

      - name: Pytest-cov comment
        uses: MishaKav/pytest-coverage-comment@main
        with:
          pytest-xml-coverage-path: ./coverage.xml
          junitxml-path: ./coverage-junit.xml